export const tagTypes = [
  "allMainCategory",
  "single-main-category",
  "all-category",
  "single-category",
  "all-sub-category",
  "single-sub-category",
  "category",
  "allContent",
  "content",
  "allProduct",
  "view-product",
  "update-product",
  "product-by-key-word",
  "User",
  "all-order-by-key-word",
  "single-order",
];
